### ISSUE TITLE
Change document title on visibilityChange instead of window.blur

### ISSUE THREAD

**Issue by m5r** [navdeepsekhon/portfolio-generator#2]
Hi,

window.blur is not only called when switching tabs but when losing focus of the window such as clicking on the address bar or on another window. Changing the document's title on the window.blur event might not be the ideal solution.
I suggest changing the title on the visibilityChange event instead. This way, the title will only change when the user is not on the page. See [the documentation](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API).

**Comment by navdeepsekhon** [comment]
Thanks!
